version: '3.7'
services:
  postgresql:
    image: postgres:12-alpine
    ports:
      - '3306:5432'
    volumes:
      - ./data:/var/lib/postgesql
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=usertest
      - POSTGRES_PASSWORD=passwordtest